# encoding: utf-8

module Categorize
  module Constants
    module Words
      # only include words > 2 chars
      ENGLISH = %w(
        000
        page
        home
        free
        also
        about
        above
        according
        accordingly
        across
        after
        afterward
        afterwards
        again
        against
        all
        almost
        alone
        along
        already
        also
        although
        always
        among
        amongst
        amp
        and
        another
        any
        anyhow
        anyone
        anything
        anywhere
        apr
        are
        aug
        around
        became
        because
        become
        becomes
        becoming
        been
        before
        beforehand
        began
        behind
        being
        below
        beside
        besides
        between
        beyond
        both
        but
        can
        cannot
        certain
        com
        could
        days ago
        dec
        did
        does
        down
        during
        each
        edu
        either
        else
        elsewhere
        enough
        especially
        est
        etc
        even
        ever
        every
        everyone
        everything
        everywhere
        example
        except
        feb
        few
        fewer
        finally
        find
        following
        for
        former
        formerly
        from
        further
        furthermore
        generally
        get
        given
        had
        has
        have
        having
        hence
        henceforth
        her
        here
        hereafter
        hereby
        herein
        hereupon
        hers
        herself
        him
        himself
        his
        hours ago
        how
        however
        http
        inc
        include
        included
        includes
        including
        indeed
        instead
        into
        its
        itself
        jan
        jul
        know
        known
        later
        latterly
        ldquo
        llc
        lquo
        least
        less
        many
        mar
        may
        maybe
        mdash
        meanwhile
        might
        miss
        more
        moreover
        most
        mostly
        much
        must
        myself
        nbsp
        ndash
        near
        nearly
        neither
        never
        nevertheless
        next
        nobody
        non
        none
        nonetheless
        nor
        not
        nothing
        nov
        now
        nowhere
        oct
        off
        often
        once
        one
        only
        onto
        org
        other
        others
        otherwise
        our
        ours
        ourselves
        out
        over
        overall
        own
        part
        particularly
        parts
        per
        perhaps
        probably
        quot
        rather
        rdquo
        rquo
        said
        same
        seem
        seemed
        seeming
        seemingly
        seems
        sep
        set
        several
        she
        should
        similar
        since
        site
        some
        somehow
        someone
        something
        sometime
        sometimes
        somewhat
        somewhere
        still
        such
        than
        that
        the
        their
        them
        themselves
        then
        thence
        thenceforth
        there
        thereafter
        thereby
        therefore
        therein
        thereupon
        these
        they
        this
        those
        though
        through
        throughout
        thru
        thus
        together
        too
        took
        toward
        towards
        two
        under
        unless
        unlike
        unlikely
        until
        upon
        url
        use
        used
        using
        usually
        various
        very
        via
        want
        was
        way
        well
        were
        what
        whatever
        when
        whence
        whenever
        where
        whereafter
        whereas
        whereby
        wherein
        whereupon
        wherever
        whether
        which
        while
        whither
        who
        whoever
        whole
        whom
        whomever
        whose
        why
        will
        with
        within
        without
        would
        www
        yes
        yet
        you
        your
        yours
        yourself
        yourselves
      )
    SPANISH = %w(
        acuerdo
        adelante
        ademas
        adrede
        ahi
        ahora
        alli
        alrededor
        antano
        ante
        antes
        apenas
        aproximadamente
        aquel
        aquella
        aquellas
        aquello
        aquellos
        aqui
        arribaabajo
        asi
        aun
        aunque
        bajo
        bastante
        bien
        breve
        casi
        cerca
        claro
        como
        con
        conmigo
        contigo
        contra
        cual
        cuales
        cuando
        cuanta
        cuantas
        cuanto
        cuantos
        debajo
        del
        delante
        demasiado
        dentro
        deprisa
        desde
        despacio
        despues
        detras
        dia
        dias
        donde
        dos
        durante
        ella
        ellas
        ellos
        encima
        enfrente
        enseguida
        entre
        esa
        esas
        ese
        eso
        esos
        esta
        estado
        estados
        estan
        estar
        estas
        este
        esto
        estos
        excepto
        final
        fue
        fuera
        fueron
        general
        gran
        habia
        habla
        hablan
        hace
        hacia
        han
        hasta
        hay
        horas
        hoy
        incluso
        informo
        junto
        lado
        las
        lejos
        los
        luego
        mal
        mas
        mayor
        medio
        mejor
        menos
        menudo
        mia
        mias
        mientras
        mio
        mios
        mis
        mismo
        mucho
        muy
        nada
        nadie
        ninguna
        nos
        nosotras
        nosotros
        nuestra
        nuestras
        nuestro
        nuestros
        nueva
        nuevo
        nunca
        otra
        otros
        pais
        para
        parte
        pasado
        peor
        pero
        poco
        por
        porque
        pronto
        proximo
        puede
        qeu
        que
        quien
        quienes
        quiza
        quizas
        raras
        repente
        salvo
        segun
        ser
        sera
        sido
        siempre
        sin
        sobre
        solamente
        solo
        son
        soyos
        supuesto
        sus
        suya
        suyas
        suyo
        tal
        tambien
        tampoco
        tarde
        temprano
        tiene
        todavia
        todo
        todos
        tras
        tus
        tuya
        tuyas
        tuyo
        tuyos
        una
        unas
        uno
        unos
        usted
        ustedes
        veces
        vez
        vosotras
        vosotros
        vuestra
        vuestras
        vuestro
        vuestros
        tudo
        dise
        dicas
        muito
      )
      FRENCH = %w(
        des
        les
        mais
        pour
      )
      COMMON = ENGLISH | SPANISH | FRENCH
      ASIAN_SPACE_CHARS = [
        '\302\267',
        '\343\200\201',
        '\343\200\202',
        '\343\203\273',
        '\357\274\201'
      ].join('|')
      SPLIT_REGEX_STR = '[^[:word:]]|[[:punct:]]|' +
          Constants::Words::ASIAN_SPACE_CHARS
      SPLIT_REGEX = Regexp.new SPLIT_REGEX_STR.force_encoding('utf-8')
    end
  end
end
